### ISSUE TITLE
Order?

### ISSUE THREAD

**Issue by rugk** [borgbackup/community#14]
Can't you specify a better order than the current "last come – last served" ordering? Maybe alphabetically or so would be fairer?

**Comment by anarcat** [comment]
i agree.

**Comment by n-st** [comment]
Might also be useful to group the links by purpose (e.g. "Installation", "Testing/Benchmarks", "Automation", "Graphical Front-ends", etc).

**Comment by rugk** [comment]
Yeah good idea. So any comment by @enkore or so?

**Comment by ThomasWaldmann** [comment]
someone make a PR, please.

**Comment by rugk** [comment]
For what? Order and/or headings?

**Comment by ThomasWaldmann** [comment]
Headings. I think strict alphabetical order is maybe worse (for the reader) than some opinionated order.

**Comment by rugk** [comment]
opinionated? Currently it's just the last goes to the bottom…

**Comment by ThomasWaldmann** [comment]
Yeah, you can keep it that way for first change.

**Comment by n-st** [comment]
I've had a go at categorising the entries; see e92afac.
The order within each category is the same as it was before (for lack of a better ordering scheme).

Let me know if you agree with the category names and the new preamble text; they're really only a suggestion.

**Comment by anarcat** [comment]
@n-st that seems like a good idea - where is that commit? how can we pull it in?

**Comment by n-st** [comment]
@anarcat https://github.com/n-st/borgbackup-community/commit/e92afac4746597904a96f04d3bb1e202be9bba12

**Comment by anarcat** [comment]
@n-st can you make a formal pull request so we can move the discussion there?

**Comment by ThomasWaldmann** [comment]
Needs to be re-done due to conflicts. Sorry @n-st.

**Comment by ThomasWaldmann** [comment]
fixed by https://github.com/borgbackup/community/commit/07c026106c8f6a84c6a7eacb816e09673c7c9ef5
