### ISSUE TITLE
how to use fuse in freebsd jail (TrueNAS)

### ISSUE THREAD

**Issue by heapxor** [borgbackup/community#58]
not sure if that goes here, but can someone advice how to mount borg repo via fuse on freebsd inside jail?

thanks!

**Comment by ThomasWaldmann** [comment]
the main purpose of this repo is to maintain the link list of borg-related community projects.

guess more people would see your question if you put it there: https://github.com/borgbackup/borg (either as issue or as a discussion)

**Comment by heapxor** [comment]
@ThomasWaldmann appreciate!
